# Site settings
title: "All About Art"
email: "rohindaswani@ayraart.com"
description: "A Knowledge Company for Art Consumers"
url: "https://rohindaswani.github.io"
baseurl: "/allaboutart.github.io"
facebook_username: ""
twitter_username: ""
instagram_username: ""
github_username:  ""
deviantart_username: ""
flickr_username: ""
discus_shortname: ""
share: true

# Owner/author information
owner:
  name: "rohindaswani"
  avatar: "avatar.png"
  favicon: "favicon.ico"
  info: ""

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments :
  provider : "disqus"
  disqus :
    short_name : ""

# Internal nav
nav:
  - GALLERY: "https://rohindaswani.github.io/allaboutart.github.io/gallery/"
  - ABOUT: "https://rohindaswani.github.io/allaboutart.github.io/about/"
#  - JOURNAL: "https://rohindaswani.github.io/allaboutart.github.io/journal/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination: "./_site"
port: "4000"


# Build settings
markdown: "kramdown"
highlighter: "rouge"
permalink: "pretty"
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/journal/:title/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
gems:
 - "jekyll-paginate"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
